# Generated by Django 6.0.3 on 2026-03-28 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Combustível',
                'verbose_name_plural': 'Combustíveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=20, unique=True, verbose_name='Contribuinte')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('morada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Morada')),
                ('caixa_postal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caixa Postal')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('contato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=20, unique=True, verbose_name='Contribuinte')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Frota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('seguro', models.DateField(blank=True, null=True, verbose_name='Seguro')),
                ('seguradora', models.CharField(blank=True, max_length=150, null=True, verbose_name='Seguradora')),
                ('inspecao', models.DateField(blank=True, null=True, verbose_name='Inspeção')),
            ],
            options={
                'verbose_name': 'Frota',
                'verbose_name_plural': 'Frota',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome')),
                ('contato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('numero_fatura', models.CharField(max_length=100, verbose_name='Nº Fatura')),
                ('dinheiro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dinheiro €')),
                ('cartao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cartão €')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total €')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='Elion.fornecedor')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data_emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_inicio', models.PositiveIntegerField(default=0, verbose_name='KM Início')),
                ('km_final', models.PositiveIntegerField(default=0, verbose_name='KM Final')),
                ('km_total', models.IntegerField(default=0, verbose_name='KM Total')),
                ('litro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Litro (L)')),
                ('valor_litro', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Valor (L)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('combustivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Elion.combustivel')),
                ('frota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Elion.frota')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_combustivel', to='Elion.lancamento')),
            ],
            options={
                'verbose_name': 'Item Combustível',
                'verbose_name_plural': 'Itens de Combustível',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('contato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato')),
                ('email_recuperacao', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail recuperação')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Elion.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_elion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
        ),
    ]
